### ISSUE TITLE
rendering a dataTable using sparklines

### ISSUE THREAD

**Issue by pssguy** [htmlwidgets/sparkline#3]
Thanks for this Ramnath. It is a great way to indicate information concisely

Would it be possible to provide a more advanced example based on the table you provided

I would like to show, say, soccer results by season in a table with two columns, one the season in question and the other a sparkline of results - with a tooltip showing data from another column of the source data.frame

``` r
df <- data.frame(season=rep(1992:1993,each=5), result = c(1,0,1,-1,0,0,1,1,0,-1), goals=c(2,0,1,0,3,0,2,3,1,0))


example sparkline for one season
sparkline(df[df$season==1992,]$result,type='tristate',posBarColor="green",negBarColor="red", zeroBarColor="blue"
          ,highlightColor="orange")
```

This sparkline shows win,loss etc. which is good out of the box but it would be nice to have a tooltip that showed the goals instead. Guess, if possible, this is javascript for which I'd appreciate a hand

**Comment by pssguy** [comment]
OK here is an example. would wrap in shinyApp() but not sure wher to put df and libraries

ui.R
```{r}

library(shiny)
library(dplyr)
library(DT)
library(sparkline)

shinyUI(fluidPage(

      selectInput("team","choose team", choices= c("teamA","teamB")),
      dataTableOutput("table")

))

```

    server.R
```{r}

df <- data.frame(
  season = rep(1992:1993, each=4), 
  team= rep(c("teamA","teamB"), times=4), 
  goalDiff = c(2,0,-1,0,3,0,2,-7),stringsAsFactors=F
)

shinyServer(function(input, output) {
  
  output$table <- renderDataTable({
 
  x = df %>%
    filter(team==input$team) %>%
    group_by(team,season) %>%
    summarize(
      result = paste(goalDiff, collapse = ",")
    ) %>%
    ungroup() %>%
    select(season,result)
  
  fnDrawCallback = JS("function (oSettings, json) {
                      $('.spark:not(:has(canvas))').sparkline('html', {
                      type: 'bar',
                      zeroColor: 'black'
                      
                      });
}")

columnDefs = list(list(
  targets = c(1),
  render = JS("function(data, type, full){
              return '<span class=spark>' + data + '</span>'           
  }")
)
  )

d1 <- datatable(x, options = list(
  columnDefs = columnDefs,
  fnDrawCallback = fnDrawCallback,
  destroy = TRUE
))

d1$dependencies <- htmlwidgets:::getDependency('sparkline')
d1

  })
})


```
 destroy = TRUE gets rid of the error message but I stil have 2 issues

a) When a new team is selected the existing table remains, albeit filled with correct data
b) The roll over no longer shows a value. Running the code outside shiny with a hard-coded input$team e.g. teamA does not have this issue

**Comment by ramnathv** [comment]
I will not be able to get to this before the weekend. If I come up with a solution, I will let you know.

**Comment by pssguy** [comment]
tx
Likewise

**Comment by bthieurmel** [comment]
I don't know if it's still relevant, but you can fix the tooltip roll over bug, you can just add quickly this : 

````
shinyUI(fluidPage(
  
  tags$head(
    tags$style(HTML("
    .jqstooltip{
        box-sizing: content-box;
    }"))
    ),
  
  selectInput("team","choose team", choices= c("teamA","teamB")),
  dataTableOutput("table")
  
))
````
You can find the global solution on https://github.com/gwatts/jquery.sparkline/issues/89

**Comment by Alainafox** [comment]
Thinks for the example you give above, but I encounter some problems when running your code ,This is the code : 
df <- data.frame(
  season = rep(1992:1993, each=5), 
  result = c(1,0,1,-1,0,0,1,1,0,-1), 
  goals = c(2,0,1,0,3,0,2,3,1,0)
)

library(dplyr)
x = df %>%
  group_by(season) %>%
  summarize(
    result = paste(result, collapse = ","),
    goals = paste(goals, collapse = ",")
  )

library(sparkline)
library(DT)
columnDefs = list(list(
  targets = c(1, 2),
  render = JS("function(data, type, full){
    return '<span class=spark>' + data + '</span>'           
  }")
))

fnDrawCallback = JS("function (oSettings, json) {
  $('.spark:not(:has(canvas))').sparkline('html', {
    type: 'bar',
    highlightColor: 'orange'
  });
}")

d1 <- datatable(x, options = list(
  columnDefs = columnDefs,
  fnDrawCallback = fnDrawCallback
))
d1$dependencies <- htmlwidgets:::getDependency('sparkline')
d1

but it dose not show me a graph,so would you please help me with that? Thanks
![snap1](https://cloud.githubusercontent.com/assets/10172116/8620854/e4301bc2-2754-11e5-84d1-eeb60ff174e9.png)

maybe it is because the version change of DT?

**Comment by alphankirayoglu** [comment]
@Alainafox Did you manage to resolve this issue? I get the same output as you did when I ran @ramnathv's code.

Versions of packages
 htmlwidgets   0.5   CRAN (R 3.1.3)  
 sparkline     1.0      Github (htmlwidgets/sparkline@8637f41)

**Comment by rob-flatiron** [comment]
@Alainafox :  Had the same problem as you when attempting to recreate the above example.

For me, the issue was that
```
d1$dependencies <- htmlwidgets:::getDependency('sparkline')
```
was overwriting the "datatables" and "datatables-default" dependencies that were created in the previous statement.   I patched this and got my dataTable to show up by modifying that line to the following:

```
d1$dependencies <- append(d1$dependencies, htmlwidgets:::getDependency('sparkline'))
```

**Comment by githubfun** [comment]
I can't reproduce the example, the goals column is not rendered..
![2015-09-29-194833_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4968931/10181232/943b4820-66e3-11e5-8fd9-a06536fe58ce.png)

**Comment by fbreitwieser** [comment]
Thanks @ramnathv for the example with the precise comments on the steps. Thanks @rob-flatiron for the fix of the dependency!

**Comment by timelyportfolio** [comment]
going to close, since this seems resolved.  Thanks to all those who participated.  `sparkline` is going to CRAN.  Please contribute issues, tests, examples to #17.
